package com.ljs.demo.pojo.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Cityinfo implements Serializable {

    private static final long serialVersionUID = -6970675031171558256L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITYINFO.CITYINFOID
     *
     * @mbggenerated Fri May 25 00:11:02 CST 2018
     */
    private Integer cityinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITYINFO.UUID
     *
     * @mbggenerated Fri May 25 00:11:02 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITYINFO.PARENTID
     *
     * @mbggenerated Fri May 25 00:11:02 CST 2018
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITYINFO.AREA
     *
     * @mbggenerated Fri May 25 00:11:02 CST 2018
     */
    private String area;//地区

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITYINFO.PROVINCE
     *
     * @mbggenerated Fri May 25 00:11:02 CST 2018
     */
    private String province;//省份

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITYINFO.CITYNAME
     *
     * @mbggenerated Fri May 25 00:11:02 CST 2018
     */
    private String cityname;//城市名

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITYINFO.CITYPHOTO
     *
     * @mbggenerated Fri May 25 00:11:02 CST 2018
     */
    private String cityphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITYINFO.CITYINFO
     *
     * @mbggenerated Fri May 25 00:11:02 CST 2018
     */
    private String cityinfo;//城市信息

    /**
     * 状态1  热门城市 0  普通城市
     */
    private Integer status;

}
