package com.ljs.demo.pojo.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Evaluate implements Serializable {

    private static final long serialVersionUID = -6970675031171558256L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATE.EVALUATEID
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    private Integer evaluateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATE.UUID
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATE.MANNER
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    private String manner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATE.DESCRIPTION
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATE.MAJOR
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATE.FACE
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    private String face;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATE.REMARK
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    private String remark;

}
