package com.ljs.demo.pojo.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Journey implements Serializable{

    private static final long serialVersionUID = -6970675031171558256L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.TOURNEYID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private Integer tourneyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.UUID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.TOURORDERID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private Integer tourorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.JOURNEYDATE
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private Date journeydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.JOURNEYSERVICE
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private String journeyservice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.JOURNEYPRICE
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private String journeyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.JOURNEYSERINFO
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private String journeyserinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOURNEY.TOURNEYID
     *
     * @return the value of JOURNEY.TOURNEYID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public Integer getTourneyid() {
        return tourneyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOURNEY.TOURNEYID
     *
     * @param tourneyid the value for JOURNEY.TOURNEYID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public void setTourneyid(Integer tourneyid) {
        this.tourneyid = tourneyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOURNEY.UUID
     *
     * @return the value of JOURNEY.UUID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOURNEY.UUID
     *
     * @param uuid the value for JOURNEY.UUID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOURNEY.TOURORDERID
     *
     * @return the value of JOURNEY.TOURORDERID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public Integer getTourorderid() {
        return tourorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOURNEY.TOURORDERID
     *
     * @param tourorderid the value for JOURNEY.TOURORDERID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public void setTourorderid(Integer tourorderid) {
        this.tourorderid = tourorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOURNEY.JOURNEYDATE
     *
     * @return the value of JOURNEY.JOURNEYDATE
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public Date getJourneydate() {
        return journeydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOURNEY.JOURNEYDATE
     *
     * @param journeydate the value for JOURNEY.JOURNEYDATE
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public void setJourneydate(Date journeydate) {
        this.journeydate = journeydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOURNEY.JOURNEYSERVICE
     *
     * @return the value of JOURNEY.JOURNEYSERVICE
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public String getJourneyservice() {
        return journeyservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOURNEY.JOURNEYSERVICE
     *
     * @param journeyservice the value for JOURNEY.JOURNEYSERVICE
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public void setJourneyservice(String journeyservice) {
        this.journeyservice = journeyservice == null ? null : journeyservice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOURNEY.JOURNEYPRICE
     *
     * @return the value of JOURNEY.JOURNEYPRICE
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public String getJourneyprice() {
        return journeyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOURNEY.JOURNEYPRICE
     *
     * @param journeyprice the value for JOURNEY.JOURNEYPRICE
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public void setJourneyprice(String journeyprice) {
        this.journeyprice = journeyprice == null ? null : journeyprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOURNEY.JOURNEYSERINFO
     *
     * @return the value of JOURNEY.JOURNEYSERINFO
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public String getJourneyserinfo() {
        return journeyserinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOURNEY.JOURNEYSERINFO
     *
     * @param journeyserinfo the value for JOURNEY.JOURNEYSERINFO
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    public void setJourneyserinfo(String journeyserinfo) {
        this.journeyserinfo = journeyserinfo == null ? null : journeyserinfo.trim();
    }
}