package com.ljs.demo.pojo.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Journey implements Serializable{

    private static final long serialVersionUID = -6970675031171558256L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.TOURNEYID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private Integer journeyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.UUID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.TOURORDERID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private Integer tourorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.JOURNEYDATE
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private Date journeydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.JOURNEYSERVICE
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private String journeyservice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.JOURNEYPRICE
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private String journeyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOURNEY.JOURNEYSERINFO
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    private String journeyserinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOURNEY.TOURNEYID
     *
     * @return the value of JOURNEY.TOURNEYID
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */

}