package com.ljs.demo.pojo.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Scenic implements Serializable {

    private static final long serialVersionUID = -6970675031171558256L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.SCENICID
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private Integer scenicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.UUID
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.CITYINFOID
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private Integer cityinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.SCENICNAME
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String scenicname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.LEVER
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String lever;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.ADDRESS
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.SCENICPHONE
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String scenicphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.OPENHOURS
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String openhours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.TICKETSINFO
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String ticketsinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.SCENICINFO
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String scenicinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.SCENICPHOTO
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String scenicphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.SCENICMAP
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String scenicmap;

}
