package com.ljs.demo.pojo.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Scenic implements Serializable {

    private static final long serialVersionUID = -6970675031171558256L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.SCENICID
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private Integer scenicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.UUID
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.CITYINFOID
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String cityinfoid;//城市表UUID

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.SCENICNAME
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String scenicname;//景点名字

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.LEVER
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String lever;//景点等级

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.ADDRESS
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String address;//景点地址

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.SCENICPHONE
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String scenicphone;//联系电话

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.OPENHOURS
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String openhours;//开放时间(字符串，9：00-16：00)

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.TICKETSINFO
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String ticketsinfo;//（门票信息）

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.SCENICINFO
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String scenicinfo;//景点信息

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.SCENICPHOTO
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String scenicphoto;//景点照片

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCENIC.SCENICMAP
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    private String scenicmap;//景点导览图

    /**
     * 状态 1：热门景点
     */
    private String status;

}
