package com.ljs.demo.pojo.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class ServiceInfo implements Serializable {

    private static final long serialVersionUID = -6970675031171558256L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICEINFO.SERVICEID
     *
     * @mbggenerated Thu May 24 21:21:37 CST 2018
     */
    private Integer serviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICEINFO.UUID
     *
     * @mbggenerated Thu May 24 21:21:37 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICEINFO.SERVICENAME
     *
     * @mbggenerated Thu May 24 21:21:37 CST 2018
     */
    private String servicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICEINFO.SERVICEPRICE
     *
     * @mbggenerated Thu May 24 21:21:37 CST 2018
     */
    private String serviceprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICEINFO.SERVICEINFO
     *
     * @mbggenerated Thu May 24 21:21:37 CST 2018
     */
    private String serviceinfo;

}
