package com.ljs.demo.pojo.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Strategy implements Serializable {

    private static final long serialVersionUID = -6970675031171558256L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STRATEGY.STRATEGYID
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    private Integer strategyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STRATEGY.UUID
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STRATEGY.SCENICID
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    private String scenicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STRATEGY.STRATEGYNAME
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    private String strategyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STRATEGY.STRATEGYCOL
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    private String strategycol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STRATEGY.STRATEGYPHOTO
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    private String strategyphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STRATEGY.STRATEGYINFO
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    private String strategyinfo;

    /**
     * 状态1:热门景点
     */
    private Integer status;
}
