package com.ljs.demo.pojo.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Tourorder implements Serializable {

    private static final long serialVersionUID = -6970675031171558256L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOURORDER.TOURORDERID
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    private Integer tourorderid;


    /**
     * 订单编号
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOURORDER.TOURID
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    private Integer tourid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOURORDER.STARTTIME
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOURORDER.ENDTIME
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOURORDER.MANCOUNT
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    private String mancount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOURORDER.CHILDCOUNT
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    private String childcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOURORDER.JOURNEYNEED
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    private String journeyneed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOURORDER.OUDERINFO
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    private String ouderinfo;

    /**
     * 订单服务总价格
     */
    private Integer totalprice;

    /**
     * 状态 0：待审批  1：审批完成
     */
    private Integer state;
}
