package com.ljs.demo.pojo.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class ToVisitor implements Serializable {

    private static final long serialVersionUID = -6970675031171558256L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.TOVISITORID
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private Integer tovisitorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.UUID
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.PHONE
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.DEPARTURE
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String departure;//出发地

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.DESTINATION
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String destination;//目的地

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.DATE
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private Date date;//出发时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.TIMENUM
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String timenum;//共几天

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.TITLE
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String title;//同游标题

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.DETAILS
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String details;//同游说明

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.STATUS
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String status;//状态 0未结伴  1结伴中

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.PART
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private Integer part;//同行总人数

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.VISITORID
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String visitorid;//visitor表uuid

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.PRESENTPART
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private Integer presentpart;//目前人数

    private Integer state;//最新同游标识1

    private String picture;//同游图片

}
