package com.ljs.demo.pojo.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class ToVisitor implements Serializable {

    private static final long serialVersionUID = -6970675031171558256L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.TOVISITORID
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private Integer tovisitorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.UUID
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.PHONE
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.DEPARTURE
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String departure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.DESTINATION
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.DATE
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.TIMENUM
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String timenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.TITLE
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.DETAILS
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.STATUS
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.PART
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private Integer part;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.VISITORID
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private String visitorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOVISITOR.PRESENTPART
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    private Integer presentpart;

}
