package com.ljs.demo.pojo.mapper;

import com.ljs.demo.pojo.domain.Evaluate;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface EvaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    int deleteByPrimaryKey(Integer evaluateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    int insert(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    int insertSelective(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    Evaluate selectByPrimaryKey(Integer evaluateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    int updateByPrimaryKeySelective(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE
     *
     * @mbggenerated Thu May 24 23:49:43 CST 2018
     */
    int updateByPrimaryKey(Evaluate record);
}