package com.ljs.demo.pojo.mapper;


import com.ljs.demo.pojo.domain.File;
import org.apache.ibatis.annotations.Mapper;


@Mapper
public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE
     *
     * @mbggenerated Sun May 27 13:10:50 CST 2018
     */
    int deleteByPrimaryKey(Integer fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE
     *
     * @mbggenerated Sun May 27 13:10:50 CST 2018
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE
     *
     * @mbggenerated Sun May 27 13:10:50 CST 2018
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE
     *
     * @mbggenerated Sun May 27 13:10:50 CST 2018
     */
    File selectByPrimaryKey(Integer fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE
     *
     * @mbggenerated Sun May 27 13:10:50 CST 2018
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE
     *
     * @mbggenerated Sun May 27 13:10:50 CST 2018
     */
    int updateByPrimaryKey(File record);
}