package com.ljs.demo.pojo.mapper;


import com.ljs.demo.pojo.domain.Journey;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface JourneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOURNEY
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    int deleteByPrimaryKey(Integer tourneyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOURNEY
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    int insert(Journey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOURNEY
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    int insertSelective(Journey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOURNEY
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    Journey selectByPrimaryKey(Integer tourneyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOURNEY
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    int updateByPrimaryKeySelective(Journey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOURNEY
     *
     * @mbggenerated Fri May 25 02:11:50 CST 2018
     */
    int updateByPrimaryKey(Journey record);
}