package com.ljs.demo.pojo.mapper;

import com.ljs.demo.pojo.domain.Scenic;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ScenicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCENIC
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    int deleteByPrimaryKey(Integer scenicid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCENIC
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    int insert(Scenic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCENIC
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    int insertSelective(Scenic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCENIC
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    Scenic selectByPrimaryKey(Integer scenicid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCENIC
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    int updateByPrimaryKeySelective(Scenic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCENIC
     *
     * @mbggenerated Fri May 25 01:15:44 CST 2018
     */
    int updateByPrimaryKey(Scenic record);
}