package com.ljs.demo.pojo.mapper;


import com.ljs.demo.pojo.domain.Strategy;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface StrategyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STRATEGY
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    int deleteByPrimaryKey(Integer strategyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STRATEGY
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    int insert(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STRATEGY
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    int insertSelective(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STRATEGY
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    Strategy selectByPrimaryKey(Integer strategyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STRATEGY
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    int updateByPrimaryKeySelective(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STRATEGY
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    int updateByPrimaryKey(Strategy record);
}