package com.ljs.demo.pojo.mapper;


import com.ljs.demo.pojo.domain.Strategy;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface StrategyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STRATEGY
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    int deleteByPrimaryKey(Integer strategyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STRATEGY
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    int insert(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STRATEGY
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    int insertSelective(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STRATEGY
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    Strategy selectByPrimaryKey(Integer strategyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STRATEGY
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    int updateByPrimaryKeySelective(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STRATEGY
     *
     * @mbggenerated Fri May 25 01:32:15 CST 2018
     */
    int updateByPrimaryKey(Strategy record);

    /**
     * 根据城市UID查询攻略
     * @param cityUid
     * @return
     */
    List<Strategy> queryByCityUid(@Param("cityUid") String cityUid);

    /**
     * 根据景点UID查询攻略
     * @param SceUId
     * @return
     */
    List<Strategy> queryBySceUid(@Param("SceUid") String SceUId);

    /**
     * 查询热门攻略
     * @return
     */
    List<Strategy> queryHotStrategy();
}