package com.ljs.demo.pojo.mapper;


import com.ljs.demo.pojo.domain.Tourorder;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TourorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOURORDER
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    int deleteByPrimaryKey(Integer tourorderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOURORDER
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    int insert(Tourorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOURORDER
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    int insertSelective(Tourorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOURORDER
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    Tourorder selectByPrimaryKey(Integer tourorderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOURORDER
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(Tourorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOURORDER
     *
     * @mbggenerated Fri May 25 01:51:54 CST 2018
     */
    int updateByPrimaryKey(Tourorder record);

    List<Tourorder> queryOrderByTourUid(@Param("uuid") String uuid);
}