package com.ljs.demo.pojo.mapper;


import com.ljs.demo.pojo.domain.ToVisitor;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ToVisitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOVISITOR
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    int deleteByPrimaryKey(Integer tovisitorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOVISITOR
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    int insert(ToVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOVISITOR
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    int insertSelective(ToVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOVISITOR
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    ToVisitor selectByPrimaryKey(Integer tovisitorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOVISITOR
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    int updateByPrimaryKeySelective(ToVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOVISITOR
     *
     * @mbggenerated Thu May 24 20:18:00 CST 2018
     */
    int updateByPrimaryKey(ToVisitor record);

    List<ToVisitor> selectList();

    ToVisitor queryByVisitorId(String visitorid);
}